# Generated by Django 5.2.5 on 2025-08-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
